version: '3.3'

services:
  elasticsearch:
    image: elasticsearch:2.3.5
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
  castle:
    build: .
    image: realworldio/castlecms
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "8080:8080"
